name: PR - Put Items on Dynamo
on:
  push:
    branches: [ main ]

jobs:
  table-ocr-class-names:
    name: Insert Items
    uses: Sato12/test-pipelines/.github/workflows/seed_dynamo_table.yml@main
    with:
      dyn_tbl_name: eventCache
      dyn_pk: pk
      dyn_sk: sk
      dyn_items_path: src/rules.json
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_VPT_PR }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_VPT_PR }}
      