name: PR - Put Items on Dynamo
on:
  push:
    branches: [ master ]

jobs:
  table-ocr-class-names:
    name: Insert Items
    uses: ./.github/workflows/dyn_insert_reusable.yml
    with:
      dyn_tbl_name: "BDB.DYN.TBL.TRANSVCMP.REPOSITORY"
      dyn_pk: absoluteId
      dyn_script_path: "./dyn_pipeline_utils/put_items.py"
      dyn_validate_path: "./dyn_pipeline_utils/validate_duplicates.py"
      dyn_items_path: "./src/items_repositoy_types.JSON"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_VPT_PR }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_VPT_PR }}
      