name: PR - Put Items on Dynamo
on:
  push:
    branches: [ main ]

jobs:
  table-ocr-class-names:
    name: Insert Items
    uses: Sato12/test-pipelines/.github/workflows/requirements_dynamo_table.yml@main
    with:
      dyn_pk: pk
      dyn_sk: sk
      dyn_items_path: src/rules.JSON"
      